MODEL:
  # BACKBONE: 'darknet_tiny'
  BACKBONE: 'darknet53'
  ANCHOR_SIZES: [32, 64, 128, 256, 512]
  ANCHOR_STRIDES: [8, 16, 32, 64, 128]
  # ANCHOR_SIZES: [128]
DATASETS:
  TRAIN: '/cvlabdata2/home/javed/data/speed_custom/train.txt'
  VALID: '/cvlabdata2/home/javed/data/speed_custom/valid.txt'
  TEST: '/cvlabdata2/home/javed/data/speed_custom/test.txt'
  MESH_DIR: '/cvlabdata2/home/javed/data/speed_custom/models/'
  BBOX_FILE: '/cvlabdata2/home/javed/data/speed_custom/speed_bbox.json'
  MESH_DIAMETERS: [1.06]
  N_CLASS: 2
INPUT:
  # INTERNAL_WIDTH: 1280
  # INTERNAL_HEIGHT: 800
  # INTERNAL_K: [2002.2753128555178, 0, 640, 0, 2002.2753128555178, 400, 0, 0, 1]
  INTERNAL_WIDTH: 960
  INTERNAL_HEIGHT: 600
  INTERNAL_K: [1501.70648464163835, 0, 480, 0, 1501.70648464163835, 300, 0, 0, 1]
  # INTERNAL_WIDTH: 640
  # INTERNAL_HEIGHT: 400
  # INTERNAL_K: [1001.1376564277589, 0, 320, 0, 1001.1376564277589, 200, 0, 0, 1]
SOLVER:
  IMS_PER_BATCH: 16
  # 
  BASE_LR: 0.01
  MAX_ITER: 100000
  # 
  LOSS_WEIGHT_CLS: 0.01
  # LOSS_WEIGHT_REG: 0.01
  # LOSS_REG_TYPE: '2D'
  LOSS_WEIGHT_REG: 0.1
  LOSS_REG_TYPE: '3D'
  POSITIVE_TYPE: 'SSC'
  POSITIVE_LAMBDA: 1.0
  REGRESSION_TYPE: 'POINT'
  AUGMENTATION_SHIFT: 0.1
  AUGMENTATION_SCALE: 0.1
  AUGMENTATION_ROTATION: 45
  AUGMENTATION_ColorH: 0
  AUGMENTATION_ColorS: 0
  AUGMENTATION_ColorV: 0
  AUGMENTATION_Sharpen: 0
  AUGMENTATION_Smooth: 5
  AUGMENTATION_Noise: 0.1
  #AUGMENTATION_ColorH: 0.2
  #AUGMENTATION_ColorS: 0.5
  #AUGMENTATION_ColorV: 0.5
  #AUGMENTATION_Noise: 0.05
  #AUGMENTATION_Smooth: 1.0
  # AUGMENTATION_OCCLUSION: 0.5
  # AUGMENTATION_BACKGROUND_DIR: './data/SUN2012pascalformat/JPEGImages/'
TEST:
  IMS_PER_BATCH: 1
  CONFIDENCE_TH: 0.3
